FROM python:3.11

ENV PYTHONUNBUFFERED=1

EXPOSE 8000

WORKDIR /app

COPY requirements.txt .

RUN pip3 install -r requirements.txt

COPY . .

RUN pip3 install django

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]
